// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\acer\Desktop\scratch\repo\scratch_repo_interface.go

// Package repo is a generated GoMock package.
package repo

import (
	reflect "reflect"
	domain "scratch/core/domain"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockScratchRepoInterface is a mock of ScratchRepoInterface interface.
type MockScratchRepoInterface struct {
	ctrl     *gomock.Controller
	recorder *MockScratchRepoInterfaceMockRecorder
}

// MockScratchRepoInterfaceMockRecorder is the mock recorder for MockScratchRepoInterface.
type MockScratchRepoInterfaceMockRecorder struct {
	mock *MockScratchRepoInterface
}

// NewMockScratchRepoInterface creates a new mock instance.
func NewMockScratchRepoInterface(ctrl *gomock.Controller) *MockScratchRepoInterface {
	mock := &MockScratchRepoInterface{ctrl: ctrl}
	mock.recorder = &MockScratchRepoInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScratchRepoInterface) EXPECT() *MockScratchRepoInterfaceMockRecorder {
	return m.recorder
}

// CreateScratch mocks base method.
func (m *MockScratchRepoInterface) CreateScratch(ctx *gin.Context, req *domain.Scratch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScratch", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateScratch indicates an expected call of CreateScratch.
func (mr *MockScratchRepoInterfaceMockRecorder) CreateScratch(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScratch", reflect.TypeOf((*MockScratchRepoInterface)(nil).CreateScratch), ctx, req)
}
